'''
Base ALNS with simple descent acceptance and roulette wheel operator selection.
Destroy: random removal, worst removal.
Repair: greedy insertion.
Based on: Ropke & Pisinger (2006), doi: 10.1287/trsc.1050.0135.

'''

class ALNS:
    def __init__(self, inst: CVRPInstance):
        self.inst = inst

        # destory and repair operation lists
        self.D = [self.random_removal, self.worst_removal] # ya3ni random index 0, worst 1
        self.R = [self.greedy_insert] # greedy index 0, the other index 1

        # weights for each heuristic
        # 1 because at the start they're all equally likely to be selected
        self.dest_weights = [1.0] * len(self.D)
        self.rep_weights = [1.0] * len(self.R)

        # initializing scores
        self.dest_scores = [0.0] * len(self.D)
        self.rep_scores = [0.0] * len(self.R)
        self.dest_usage = [0] * len(self.D)
        self.rep_usage = [0] * len(self.R)

    def solve(self, initial_solution, n_iter=1000, n_seg=100):
        # before loop initialize solution first
        current_sol = copy_solution(initial_solution)
        best_sol = copy_solution(initial_solution)
        best_obj = objective(best_sol, self.inst.dist)
        current_obj = best_obj

        for i in range(n_iter):
            self.reset_scoresNusage() # reset current score (to 0 as the start of every segment)
            # picking new q for each segment
            q = random.randint(5,15)

            for j in range(n_seg):

                # select operator -> call roulette wheel here
                # index here cuz we got a D list and R list (each holds an op)
                dest_index = self.roulette_wheel(self.dest_weights)
                rep_index = self.roulette_wheel(self.rep_weights)

                # increment usage after selection
                self.dest_usage[dest_index] += 1
                self.rep_usage[rep_index] += 1

                # apply destroy + repair
                temp_dest, removed = self.destroy(current_sol, dest_index, q)
                candidate_sol = self.repair(temp_dest, rep_index, removed) # we gotta send in the list of removed customers
                candidate_obj = objective(candidate_sol, self.inst.dist)

                accepted = self.accept(current_obj, candidate_obj)
                reward = self.get_reward(candidate_obj, current_obj, best_obj, accepted)

                if accepted:
                    current_sol = candidate_sol # updating current to candidate
                    current_obj = candidate_obj

                    if current_obj < best_obj: # compare to global best
                        best_sol = copy_solution(current_sol)
                        best_obj = current_obj
                # update regardless of acceptance of rejection
                self.dest_scores[dest_index] += reward
                self.rep_scores[rep_index] += reward

            # after each segment
            self.update_weights(self.dest_weights, self.dest_scores, self.dest_usage)
            self.update_weights(self.rep_weights, self.rep_scores, self.rep_usage)

        return best_sol

    def roulette_wheel(self, op_weights):
        # getting probabilities of each op based on weight formula
        # weight of op / sum of all weights of all ops
        probs = [0.0] * len(op_weights) # same length

        for i in range(len(op_weights)):
            probs[i] = op_weights[i] / sum(op_weights)

        # using random.choice p tells numpy the prob of picking that index
        # random value is generated by numpy b/w 0 - 1 and maps it to the index
        # based on those probs (higher prob -> bigger slice in wheel -> high likelyhood of being landed on)
        index = np.random.choice(range(len(op_weights)), p=probs)

        return index # will be used to pick the op from self.D or self.R

    def update_weights(self, weights, scores, usage,r=0.1):
        for w in range(len(weights)):
            if usage[w] > 0: # to avoid division by 0
                weights[w] = weights[w]*(1-r) + r*(scores[w]/usage[w])

    def random_removal(self, solution, q):
        sol = copy_solution(solution)
        removed = []
        # simple to flatten all customers from sol into one list
        flat_sol = [cust for route in sol for cust in route]
        # picking q customers randomly
        removed = random.sample(flat_sol,q)

        # iterating over to remove them from their routes
        for i in range(len(sol)):
            # for each route only keeping cust that aren't in removed
            sol[i] = [cust for cust in sol[i] if cust not in removed]

        sol = [route for route in sol if route] # filtering out the empty routes []
        # recall: route if nonempty evaluates to true

        return sol, removed

    def worst_removal(self, solution, q):
        p = 6 # randomization parameter
        sol = copy_solution(solution)
        removed = []

        costs = self.compute_costs4worst(sol)

        while q > 0:
            # getting selected customer from the costs list using index
            y = random.random() # random float value b/w 0.0 & 1.0
            index = min(int(y**p * len(costs)), len(costs) - 1) # note this clamps any issues when y gets close to 1.0 which could = len(costs)

            # getting selected customer from the costs list
            selected_cust = costs[index][1]
            removed.append(selected_cust)

            for j in range(len(sol)):
                sol[j] = [cust for cust in sol[j] if cust != selected_cust]

            # empty route removal
            sol = [route for route in sol if route]

            # recomputing costs -> rebuilding
            costs = self.compute_costs4worst(sol)

            q -= 1

        return sol, removed

    def greedy_insert(self, temp_dest, removed):
        sol = copy_solution(temp_dest)

        # inserting the hardest customers first
        sorted_removed = sorted(removed, key=lambda c: self.inst.demands[c], reverse=True)

        for cust in sorted_removed:
            best_cost = float('inf')
            best_route = None
            best_pos = None

            for r, route in enumerate(sol):
                for pos in range(len(route) + 1):
                    cost = self.insert_cost(cust, route, pos)
                    if cost < best_cost: # is cheap to insert?
                        best_cost = cost
                        best_route = r
                        best_pos = pos

            # inserting at best_pos found
            if best_route is not None:
              sol[best_route].insert(best_pos, cust)
            else:
              # there is no feasible position in the existing routes -> creating a solo route
              sol.append([cust])
              #print(f'Warning! no feasible position for customer {cust} so creating solo route')

        return sol

    def insert_cost(self, cust, route, pos): # similar to cost4worst only capacity consideration
      prev  = route[pos-1] if pos > 0 else 0
      after = route[pos] if pos < len(route) else 0

      demand = route_demand(route, self.inst.demands)
      # debugging print(f"  cust={cust} demand={self.inst.demands[cust]} route_demand={demand} capacity={self.inst.capacity}")

      if demand + self.inst.demands[cust] > self.inst.capacity:
          return float('inf')

      return self.inst.dist[prev][cust] + self.inst.dist[cust][after] - self.inst.dist[prev][after]

    # def X_insert(): maybe another insert here? maybe regret if there is time

    def destroy(self, sol, dest_index, q):
        return self.D[dest_index](sol, q)

    def repair(self, sol, rep_index, removed):
        return self.R[rep_index](sol, removed)

    def accept(self, current_obj, candidate_obj):
        return candidate_obj < current_obj

    def get_reward(self, candidate_obj, current_obj, best_obj, accepted):
        # initializing the reward values
        sigma1 = 33
        sigma2 = 9
        # sigma3 = 13 not really used - because it requires simulated annealing acceptance

        if accepted:
            if candidate_obj < best_obj: # then new global best
                return sigma1
            else:
                return sigma2 # better than current
        else:
            return 0 # rejected

    def reset_scoresNusage(self):
        self.dest_scores = [0.0] * len(self.D)
        self.rep_scores = [0.0] * len(self.R)
        self.dest_usage = [0] * len(self.D)
        self.rep_usage = [0] * len(self.R)

    def compute_costs4worst(self, sol):
        # cost(i) = how much does the route shorten if we remove the customer i
        # formula from paper: dist(prev, i) + dist(i, after) - dist(prev, after)
        # basically the idea is what we pay to go through this cust i, minus what we'd pay skipping it

        costs = []
        # getting neighbors of customer on route + calcuating costs based on formula in paper
        for route in sol:
            for pos in range(len(route)):
                cust_id = route[pos] # customer id (not position)

                # depot is 0 so boundary customers connect to depot
                if pos == 0 : # if current cust is the first in the route
                    prev = 0
                else:
                    prev = route[pos-1]

                if pos == len(route) - 1: # if cust is the last in route
                    after = 0
                else:
                    after = route[pos+1]

                # high cost meaning its expensive to keep cust where they are -> good to remove

                cost_value = self.inst.dist[prev][cust_id] + self.inst.dist[cust_id][after] - self.inst.dist[prev][after]
                costs.append((cost_value, cust_id))


        costs.sort(reverse=True) # storing with most expensive at cust at the start

        return costs